server.port=8080
spring.application.name=jvm-demo
management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.metrics.tags.env=${ENV:dev}
