{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "jvm-demo.fullname" . }}
  labels:
    {{- include "jvm-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "jvm-demo.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: {{ .Values.monitoring.serviceMonitor.path }}
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
